version: 0
metadata:
  name: TC-Github Testing
  description: Used to support `npm run checkStaging`
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        env: true
        events:
          - push
    payload:
      command:
        - case $GITHUB_HEAD_REF in refs/tags/*); echo 'hi!'; esac
      image: 'busybox'
      maxRunTime: 60
    metadata:
      name: dummy
      description: dummy task to validate tc-github staging
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
