version: 0
metadata:
  name: TC-Github Testing
  description: Used to support `npm run checkStaging`
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: 'gce-provider'
    workerType: 'gce-worker-test'
    extra:
      github:
        events:
          - push
        excludeBranches:
          - something-never-pushed-to
    payload:
      command: [['echo', 'hello, world']]
      maxRunTime: 60
    metadata:
      name: dummy
      description: dummy task to validate tc-github staging
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
