version: 1
tasks:
  - provisionerId: aws-provisioner-v1
    workerType: github-worker
    $match:
      'tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"]':
        taskId: {$eval: as_slugid("pr_task")}
        scopes:
          - secrets:get:project/taskcluster/testing/taskcluster-github
    payload:
      maxRunTime: 3600
      image: node
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.pull_request.head.ref}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.pull_request.head.sha}} && npm
          install . && npm test
    metadata:
      name: ''
      description: ''
      owner: '${event.pusher.name}@users.noreply.github.com'
      source: ${event.repository.url}
policy:
  pullRequests: public
